add_newline = true

format = """
$username@$hostname$fill$directory$git_branch$git_status
$character
"""

# === Username / Host ===
[username]
show_always = true
format = "[$user]($style)"
style_user = "bold dimmed purple"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "dimmed #B794F4"

# === Directory ===
[directory]
truncation_length = 3
truncation_symbol = "…/"
format = "[$path]($style) "
style = "bold #C4B5FD"

# === Git ===
[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "#9F7AEA"

[git_status]
style = "dimmed #A78BFA"
format = "([$all_status$ahead_behind]($style)) "

# === Prompt Symbol ===
[character]
success_symbol = "[❯](bold #C4B5FD)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold #C4B5FD)"

